### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kesterk**
Using tabula-py for multiple tables extraction from PDF.

### CODE REVIEW

**Comment by otseobande** [comment]
@kesterk You have made good progress and I must commend how fast you came up with a solution. I have a some feedback I would like you to look into.

- Your PR title is should be descriptive of the task you're working on.
- The table headers are quite important but I noticed you disabled it.
- I noticed you didn't extract the `Analysis of Total Assets` table.

I noticed you used the `areas` parameter being passed to the `read_pdf` function. Can you give me more context as to it's use?

**Comment by kesterk** [comment]
Thanks for the feedback. 

- The Analysis of Total Assets` table was too small to be detected by tabula-py, but I am working on using camelot-py that uses open cv for line and border detection.
- The areas parameter is to point tabula-py to a specific area of the pdf page, without this, it merges two tables together. But I am also working on that too, so that table extraction can be extracted irrespective of the table layout.
- The table headers had white space, so it becomes difficult to work with. I will still work on that.

Thanks.

**Comment by kesterk** [comment]
Extracted tables from pdf files stored in same folder.
Also extracted tables from two pdf files using different parameter setting. 
Was able to extract all the tables in the pdf file,though not 100% accurate.

**Comment by otseobande** [comment]
@kesterk I actually wanted you to focus on the Baronsmead PDF file.

**Comment by kesterk** [comment]
I extracted all the tables from Baronsmead PDF file including 

> analysis of total assets.
The only way I could check if what I did was generic was to write a function that search for pdf files in a folder and try to extract tables from the pdf files to excel sheet. Thanks.

**Pull request closed without merging**
